name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-stg:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: Staging
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}

    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2

      - name: Setup GCloud ‚öôÔ∏è
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "349.0.0"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build üîß
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

      - name: Deploy üöÄ
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.SHA }}
          region: ${{ secrets.GCP_REGION }}

  deploy-prod:
    name: Deploy to Production
    needs: [deploy-stg]
    runs-on: ubuntu-latest
    environment:
      name: Production
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}

    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2

      - name: Setup GCloud ‚öôÔ∏è
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "349.0.0"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build üîß
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

      - name: Deploy üöÄ
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.SHA }}
          region: ${{ secrets.GCP_REGION }}
