name: GitHub Actions

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Setup Python ğŸ
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Restore pip cache ğŸ’¾
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies âš™ï¸
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Run linting ğŸ§ª
        run: pre-commit run --all-files

  snyk-scan:
    name: Snyk Scan

    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities ğŸ›¡ï¸
        uses: snyk/actions/python@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning ğŸ“¡
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif

  deploy-stg:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [lint, snyk-scan]
    if: ${{ github.ref == 'refs/heads/master' }}
    environment:
      name: Staging
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Setup GCloud âš™ï¸
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "349.0.0"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build ğŸ”§
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

      - name: Deploy ğŸš€
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.SHA }}
          region: ${{ secrets.GCP_REGION }}

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [deploy-stg]
    if: ${{ github.ref == 'refs/heads/master' }}
    environment:
      name: Production
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Setup GCloud âš™ï¸
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "349.0.0"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build ğŸ”§
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

      - name: Deploy ğŸš€
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.SHA }}
          region: ${{ secrets.GCP_REGION }}
