name: update-l10n

on:
  push:
    branches: [master]

jobs:
  update-l10n:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Python ðŸ
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Restore pip cache ðŸ’¾
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Babel ðŸŒ
        run: |
          pip3 install -U pip
          pip3 install Babel==2.9.0

      - name: Update localization source file ðŸ“„
        run: |
          pybabel extract bot.py pdf_bot/ -o locale/pdf_bot.pot
          pybabel update -l locale -i locale/pdf_bot.pot -o locale/en_GB/LC_MESSAGES/pdf_bot.po
          echo NUM_DIFFS=$(git diff --shortstat | egrep -o '[0-9]+ i' | egrep -o '[0-9]+') >> $GITHUB_ENV

      - name: Commit changes ðŸ†•
        if: env.NUM_DIFFS > 1
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update localization source file
          file_pattern: locale/en_GB/LC_MESSAGES/pdf_bot.po
          push_options: --force
