name: Update l10n Sources

on:
  push:
    branches: [master]

jobs:
  update-l10n-source:
    name: Update l10n Sources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Python ðŸ
        id: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9.7"

      - name: Install Poetry ðŸ“¦
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache virtual environment ðŸ’¾
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-${{ steps.setup-python.outputs.python-version }}-

      - name: Install dependencies âš™ï¸
        run: poetry install --no-interaction --no-root

      - name: Update localization source file ðŸ“„
        run: |
          source .venv/bin/activate
          pybabel extract main.py pdf_bot/ -o locale/pdf_bot.pot
          pybabel update -l locale -i locale/pdf_bot.pot -o locale/en_GB/LC_MESSAGES/pdf_bot.po
          echo NUM_DIFFS=$(git diff --shortstat | egrep -o '[0-9]+ i' | egrep -o '[0-9]+') >> $GITHUB_ENV

      - name: Commit changes ðŸ†•
        if: env.NUM_DIFFS > 1
        uses: stefanzweifel/git-auto-commit-action@v4.13.1
        with:
          commit_message: "ci: update localization source file [skip ci]"
          file_pattern: locale/en_GB/LC_MESSAGES/pdf_bot.po
          push_options: --force

      - name: Upload sources and download translations ðŸŒ
        if: env.NUM_DIFFS > 1
        uses: crowdin/github-action@1.4.7
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          commit_message: "feat: new translations"
          create_pull_request: true
          pull_request_title: "feat: new translations"
          pull_request_labels: l10n
          config: ./crowdin.yml
          source: locale/en_GB/LC_MESSAGES/pdf_bot.po
          translation: /locale/%locale_with_underscore%/LC_MESSAGES/pdf_bot.po
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
