name: Update-l10n

on:
  push:
    branches: [master]

jobs:
  update-l10n:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Python ğŸ
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install Babel ğŸŒ
        run: |
          pip3 install -U pip
          pip3 install Babel==2.9.0

      - name: Update localization source file ğŸ“„
        run: |
          pybabel extract bot.py pdf_bot/ -o locale/pdf_bot.pot
          pybabel update -l locale -i locale/pdf_bot.pot -o locale/en_UK/LC_MESSAGES/pdf_bot.po

      - name: Create Pull Request ğŸ†•
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update localization source file
          branch: update/l10n-source-file
          title: Update localization source file
